""""CreateInitModel"

Revision ID: a41207d41c10
Revises:
Create Date: 2024-03-21 01:24:56.829478+09:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql
from sqlalchemy_utils.types import ChoiceType, PasswordType

from models import StubType

# revision identifiers, used by Alembic.
revision: str = 'a41207d41c10'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form',
    sa.Column('id', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('title', mysql.TEXT(), nullable=False, comment='タイトル'),
    sa.Column('description', mysql.TEXT(), nullable=False, comment='説明'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.PrimaryKeyConstraint('id'),
    comment='フォーム',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin'
    )
    op.create_table('user',
    sa.Column('id', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('lineUserID', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=48), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lineUserID'),
    comment='ユーザー',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin'
    )
    op.create_table('admin',
    sa.Column('id', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('username', sa.String(length=255, collation='utf8mb4_bin'), nullable=True),
    sa.Column('password', PasswordType(), nullable=True),
    sa.Column('user_id', mysql.SMALLINT(unsigned=True), nullable=True, comment='ユーザー'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    comment='管理者',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin'
    )
    op.create_table('answer',
    sa.Column('id', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('form_id', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.ForeignKeyConstraint(['form_id'], ['form.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='回答収集のマスタ',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin'
    )
    op.create_table('formstub',
    sa.Column('id', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('title', mysql.VARCHAR(255), nullable=False, comment='タイトル'),
    sa.Column('description', mysql.TEXT(), nullable=True, comment='説明'),
    sa.Column('order', mysql.SMALLINT(unsigned=True), nullable=False, comment='formの順番'),
    sa.Column('type', ChoiceType(choices=StubType, impl=mysql.TINYINT()), nullable=False, comment='formの種類'),
    sa.Column('form_id', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.ForeignKeyConstraint(['form_id'], ['form.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='画像用のフォームの一部',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin'
    )
    op.create_table('imganswer',
    sa.Column('id', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('form_stub_id', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('answer_id', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], ),
    sa.ForeignKeyConstraint(['form_stub_id'], ['formstub.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='画像回答収集',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imganswer')
    op.drop_table('formstub')
    op.drop_table('answer')
    op.drop_table('admin')
    op.drop_table('user')
    op.drop_table('form')
    # ### end Alembic commands ###
