""""AlterAnswer"

Revision ID: 865a1d01192f
Revises: a41207d41c10
Create Date: 2024-03-21 06:23:01.394247+09:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql
from sqlalchemy_utils.types import PasswordType

# revision identifiers, used by Alembic.
revision: str = '865a1d01192f'
down_revision: Union[str, None] = 'a41207d41c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin', 'password',
               existing_type=sa.VARBINARY(length=1024),
               type_=PasswordType(),
               existing_nullable=True)
    op.add_column('answer', sa.Column('start', mysql.DATETIME(timezone=True), nullable=False))
    op.add_column('answer', sa.Column('end', mysql.DATETIME(timezone=True), nullable=False))
    op.alter_column('formstub', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=255),
               nullable=True,
               existing_comment='タイトル')
    op.add_column('imganswer', sa.Column('key', mysql.VARCHAR(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imganswer', 'key')
    op.alter_column('formstub', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=255),
               nullable=False,
               existing_comment='タイトル')
    op.drop_column('answer', 'end')
    op.drop_column('answer', 'start')
    op.alter_column('admin', 'password',
               existing_type=PasswordType(),
               type_=sa.VARBINARY(length=1024),
               existing_nullable=True)
    # ### end Alembic commands ###
