""""SaveTwoImg"

Revision ID: a35b4317a46e
Revises: 865a1d01192f
Create Date: 2024-03-22 03:25:44.047758+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy_utils.types import PasswordType

# revision identifiers, used by Alembic.
revision: str = 'a35b4317a46e'
down_revision: Union[str, None] = '865a1d01192f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin', 'password',
               existing_type=sa.VARBINARY(length=1024),
               type_=PasswordType(),
               existing_nullable=True)
    op.add_column('imganswer', sa.Column('key_be', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('imganswer', sa.Column('key_af', mysql.VARCHAR(length=128), nullable=False))
    op.drop_column('imganswer', 'key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imganswer', sa.Column('key', mysql.VARCHAR(collation='utf8mb4_bin', length=128), nullable=False))
    op.drop_column('imganswer', 'key_af')
    op.drop_column('imganswer', 'key_be')
    op.alter_column('admin', 'password',
               existing_type=PasswordType(),
               type_=sa.VARBINARY(length=1024),
               existing_nullable=True)
    # ### end Alembic commands ###
